services:
  db:
    image: postgres:16-alpine
    container_name: bankflow_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bankflow
      POSTGRES_USER: bankflow
      POSTGRES_PASSWORD: bankflow_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankflow -d bankflow"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
